select
    *
from SEISEKI
where 1=1
/*$GAKUSEKI_NO*/    AND GAKUSEKI_NO     = :GAKUSEKI_NO
/*$MATH_SCORE*/     AND MATH_SCORE      = :MATH_SCORE
/*$ENGLISH_SCORE*/  AND ENGLISH_SCORE   = :ENGLISH_SCORE
order by GAKUSEKI_NO
