insert into SEISEKI
(
/*$GAKUSEKI_NO*/      GAKUSEKI_NO
/*$MATH_SCORE*/     , MATH_SCORE
/*$ENGLISH_SCORE*/  , ENGLISH_SCORE
/*$JAPANESE_SCORE*/ , JAPANESE_SCORE
/*$SUM_SCORE*/      , SUM_SCORE
/*$AVG_SCORE*/      , AVG_SCORE
)
values
(
/*$GAKUSEKI_NO*/      :GAKUSEKI_NO
/*$MATH_SCORE*/     , :MATH_SCORE
/*$ENGLISH_SCORE*/  , :ENGLISH_SCORE
/*$JAPANESE_SCORE*/ , :JAPANESE_SCORE
/*$SUM_SCORE*/      , :SUM_SCORE
/*$AVG_SCORE*/      , :AVG_SCORE
)
