REM INSERTING into "SYSTEM"."SEISEKI_SUMMARY"
SET DEFINE OFF;
Insert into "SYSTEM"."SEISEKI_SUMMARY" (KIND,MATH_SCORE,ENGLISH_SCORE,JAPANESE_SCORE) values ('MAX',null,null,null);
Insert into "SYSTEM"."SEISEKI_SUMMARY" (KIND,MATH_SCORE,ENGLISH_SCORE,JAPANESE_SCORE) values ('AVG',null,null,null);
commit;
