CREATE TABLE ABC (SHAIN_CD varchar2(10), SHIMEI varchar2(100), UMARE DATE)
/
CREATE TABLE ZOKU (SHAIN_CD varchar2(10), SSK_CD varchar2(8), KBN char(2))
/
ALTER TABLE ABC ADD(SEX char(1))
/
ALTER TABLE ABC ADD CONSTRAINT ABC_PK PRIMARY KEY (SHAIN_CD)
/
ALTER TABLE ZOKU ADD CONSTRAINT ZOKU_PK PRIMARY KEY (SHAIN_CD, SSK_CD)
/
